version: "3.9"

services:
  gerrit_1:
    build: gerrit_1
    image: gerrit_1
    ports:
      - "39418:29418"
      - "10080:8080"
      - "10022:22"
    depends_on:
      - ldap
    container_name: gerrit_1
    environment:
      - CANONICAL_WEB_URL=http://localhost:11080

  gerrit_2:
    build: gerrit_2
    image: gerrit_2
    ports:
      - "49418:29418"
      - "11080:8080"
      - "11022:22"
    depends_on:
      - ldap
    container_name: gerrit_2
    environment:
      - CANONICAL_WEB_URL=http://localhost:10080

  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /var/gerrit/ldap/var:/var/lib/ldap
      - /var/gerrit/ldap/etc:/etc/ldap/slapd.d
    container_name: ldap


  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka-broker:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    container_name: kafka-broker
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
